<?php

namespace OC\Bundle\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{

    /**
    * Find user by email
    * @param  string email 
    * @return OC\Bundle\UserBundle\Entity\User
    */
	public function findByEmail($email)
	{
	  $qb = $this->createQueryBuilder('a');

	  $qb
	    ->where('a.email = :email')
	    ->setParameter('email', $email)
	  ;

      return $qb->getQuery()->getResult();
	  
	  
	}
}
